export { School1 } from './school-1'
export { School2 } from './school-2'
export { School3 } from './school-3'
export { School4 } from './school-4'
export { School5 } from './school-5'
export { School6 } from './school-6'
export { School7 } from './school-7'
export { School8 } from './school-8'

export { Sports1 } from './sports-1'
export { Sports2 } from './sports-2'
export { Sports3 } from './sports-3'
export { Sports4 } from './sports-4'
export { Sports5 } from './sports-5'
export { Sports6 } from './sports-6'
export { Sports7 } from './sports-7'
export { Sports8 } from './sports-8'

export { Nature1 } from './nature-1'
export { Nature2 } from './nature-2'
export { Nature3 } from './nature-3'
export { Nature4 } from './nature-4'
export { Nature5 } from './nature-5'
export { Nature6 } from './nature-6'
export { Nature7 } from './nature-7'
export { Nature8 } from './nature-8'
